version: "3"
services:
  #  service de discovery eureka
  eureka:
    container_name: eureka-service
    build: ./eureka-service
    environment:
      - EUREKA_SERVICE_PORT=60011
    ports:
      - 60011:60011

  #  service pour travel payouts gateway
  travel-payout-gateway:
    container_name: travel-payouts-gateway
    build: ./travel-payouts-gateway
    environment:
      - TRAVEL_PAYOUTS_PORT=60012
      - DISCOVERY_SERVICE_BASE_URL=http://eureka-service:60011
    ports:
      - 60012:60012

  #  service pour skyscanner gateway
  skyscanner-gateway:
    container_name: skyscanner-gateway
    build: ./skyscanner-gateway
    environment:
      - SKYSCANNER_GATEWAY_PORT=60013
      - DISCOVERY_SERVICE_BASE_URL=http://eureka-service:60011
    ports:
      - 60013:60013

  #  service pour obryan-software gateway
  obryan-software-gateway:
    container_name: obryan-software-gateway
    build: ./obryan-software-gateway
    environment:
      - OBRYAN_SOFTWARE_PORT=60014
      - DISCOVERY_SERVICE_BASE_URL=http://eureka-service:60011
    ports:
      - 60014:60014

  #  service pour touki-api gateway
  touki-api:
    container_name: touki-api
    build: ./toukiApi
    environment:
      - TOUKI_API_PORT=60010
      - DISCOVERY_SERVICE_BASE_URL=http://eureka-service:60011
    ports:
      - 60010:60010
